export const categories = [
  {
    id: "vegetables",
    name: "Vegetables",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuAMrKOlhg_mlTPfXU1ILPJnQCBu5e_zz2eyPIwsEgNVaSx0jNXboTb2FK1T6BnutRgK_JaoJCwVjN9OlIl0rcsZzCAAbBrmdLVoEGcNTQjcLJxuDXYBoIAIRHiZku_JmlTbeD_pua7BBrVCvhWB7UWGwxa_BdSuyOFghkE345UzpJRp3SFby56BsqLcL_bQYpalUX9OlZis675NNmsm2Id9Ex3_5q1jZ0-lb9pMBypcbzilDI2EJysYwBcHgfJ64cgi0gF72AjzPJA",
  },
  {
    id: "fruits",
    name: "Fruits",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuC6aakDyqKofqUq6UorrT6_6k6pAoofUUKJ6RoMszqEunN_Cx5lI4puTxGwQnzWMPxUk7PzSCheIgqWqahnvyVEB47hYG0adVb5uiEbuHU3JZY7lyqtStcvjoqmdo4DRqrpJFtY7ZN_TQ8QV-VoGo58mirugLYrtf_-6uivlqnG7962pnZrxq6P5GS_4-MhKBANtkW8w9bL3PXGO1Wibg0rhwRJWkdarWqXYpS0rBJ0xrvHuJe3cK2epGQaPhsZWtmhjM0gJ1RS7Wk",
  },
  {
    id: "grains",
    name: "Grains",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuAVUiGBaKpjFcMbI0OVtvZYVBTzBGEBCMSOhlUlttXebAwcjJnAQGR8c4MACzaWyCs2Dckkc7hNgazsQxPnGZenVpuwvxTHxsRhwzp0iAxVcnFm_dnn4-laECkXHMcOU5pA7qB2z7kmZoxXNWpRSVG-d2YYWWkEWVRLDelYZBaqynhQKswOxcacGrcex5ilPJ15pWxVClBLDlp5T8qwmQX7vGkKvrm8iQa6TfBkIAXh6QsMq_NtKOnVcJQbbGne-kZW5CZlV3h6bdw",
  },
  {
    id: "dairy",
    name: "Dairy",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuDrsKCqnp8K2Zvoo_EDaGsLLh08TxgBTjMXCksRtr1WyD7w1Af7cSj4tghyQVMZbIcSp-3h-9U9L01PiYBwaI3ch6_v6MSryR1SyCtQ4MS7548Ao_6BRRWNL_zRthBlKLL5QRy7FWoZmUhcrsg3YO8Q-HOViFf0LcvP8NOuTISDwSMBkeZQ0rzmXCDzgwK6S_-N145OSFkqemtyEHDQJ4IMWIWKvi-73CgW03sxFhSC55RLPiO2b-hJTAGmids8eKcpZf-uiS8CW1o",
  },
  {
    id: "herbs",
    name: "Herbs",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuDj24WxO9zScxN0NgLD1n17Lf7W923tNxRAm55Q2bh8DC6m8YIQtyg2xYHWb3w-ZKXMY8V9Ne-pGxC1JhOUs56pACCcD1Cfc0uaZEuCG24fxOSiqTK6oUprXnM3gXj44G45R4-Rg0EUMU-TPfjG8UDTfBvGSZxCIMJp4p9wibjMMiZIAIY1s25u55TQFEgpBV7va-lL3q-uXWKySHd3cOLctQvor19-eRGr16QI3FR9wReoBzomWOYpU8g7ZvgwUwocTs56nr3ujgA",
  },
];

export const vendors = [
  {
    id: "mama-rose",
    name: "Mama Rose",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuDRaQqWHrexq0ia-EqpOTbE8qTyaVKsCCUXDgJ46d2Dl3u8hK44cCl53w28oWVMM0eGi1rRQnCGoN2moXT1w7R2N_s5yPZSdKcBJS4HDIFcWiF_9Gy6fJ6ZWHiljQ0W5cVBRrQtWHGYLjDEtGQDiDNRYdXKcUEzIUNlPMRMLPGZHUfman_g9uWEm7Gzic-PFhZO1PJhMtnxQg8rzmeC3XGV7xq4vCZl8_TWDhWlfvWLC0DvN4cbzvDXmN53GpueB-F2-fpztz8iwu8",
  },
  {
    id: "farmer-john",
    name: "Farmer John",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuBVYDgKhCIQ5KQLpvMj8817TTOmiwVJmkDgqfFMJg787hwfH5hdHSym1poI7wZEWHdi90UJADkY8p5cqX8cCx3kC_-F_OIjhbSR3F9gWBuqsIkDBg2BtLnVPS0ORRmYbpfB-zBgLG6CKTPftaI0UA0waAUHH-hGWYhnlx4O4zxibCj8NsUQEgt9kc-4DAmrBSBmh-liYAWrMBXmgrb-2DgP7oGgN2NqtgeJPkemQ93duc8yRzt-XobTkFLRv6ui_FlYajM0jEFzpeA",
  },
  {
    id: "auntie-agnes",
    name: "Auntie Agnes",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuAtJyf3gztKISUGmV_x6gziYHVv6k4TdASiH-lKaMWtUE2yRc0sfoSnZds5_NIz2qWjTgxbzyr7c4Qir3qpU5IXerJbBuPU5YQMChWu-nNc4MBoUek-eoW6eDPmGK9EnZs9ib6yNx5dx_8LDmiaN6pWhwjr6UwdMgDs2xobmu0aB1ZXWrIYa0NiQByTmsnX7XUW01bEEnJastsN6TxQmoGXUwufnGMx8KFyzqsuZRFvtU_H1MUlFT8e0OXxOnkWAts7GJeYLiWSC4o",
  },
  {
    id: "uncle-david",
    name: "Uncle David",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuATE088txVP3__TbPhBOywwX2zgmleZul7K1fbKjbpMkgb0LLbypTDd7NvfKsgn4vaTYskp977djhC7cnc_b5lInWQifG-oKkpqqHdeuHSj70Mdl2tTk3_9FGVg-hsqTauDTlK_GpehYaYTDavEDIY0fE0F8MbstmZhjYfjTNikaaafjzrtvjc7f77vj4GwtJEMND8Jfr88ej6zXwAZxqbsRuiCJoB2Myksx1Ib5AY_tjRoyMdqvZGrFFo7ZnpbA52cfdUQVNQRDZY",
  },
];

export const products = [
  {
    id: "p1",
    title: "Fresh Tomatoes",
    vendorId: "mama-rose",
    vendor: "Mama Rose",
    category: "Vegetables",
    categoryId: "vegetables",
    tags: ["tomato", "salad", "vegetables"],
    deliveryEstimate: "25 minutes",
    description:
      "Juicy, ripe tomatoes, perfect for salads, cooking, and snacking. Sourced directly from local farmers, ensuring freshness and quality.",
    price: "KES 150.00/kg",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuBV8gBbKDa7cnMo9Dd_h-fyu4f1jiSE04nHoEkLNmImaNTqW_itR65qLuIFDIy4loHjhJGzzmb0dRdiodmUR4SR4tObd-gXkt64n3DsrJoy1DjfS74qMY9Tfg0xfB_d8-9Nq8CQqOVLD7FqjVurOP6UI1rZCj-Qe6GCrmx87UmvQdPA6VXx_Zmhn2zxzE_Nhi0FgYDA-CnO7ZXYrbubdEE72AIpZh9pqmyWoPqkUeFvjSsWV3Sp5NDBK2wLd_VXxHmMemnOdC3EKcU",
  },
  {
    id: "p2",
    title: "Ripe Bananas",
    vendorId: "farmer-john",
    vendor: "Farmer John",
    category: "Fruits",
    categoryId: "fruits",
    tags: ["banana", "fruit", "snack"],
    description:
      "Juicy, ripe bananas — perfect for salads, cooking, and snacking. Sourced directly from local farmers, ensuring freshness and quality.",
    deliveryEstimate: "25 minutes",
    price: "KES 80.00/bunch",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuATQit1JrF5Jnyt4wkvgo4gg9AE35WZUHYu4bkP8Ug9C24i6Hq1pNoyB6sLrOU8lTrlw08oS_T1yAyCSoFN6GBDhXyWuTyePSown1zYI1IdMrIa_s7q3R85HYOD-V4TQtSPgpFWQ4LJFw-8rwhCMVpOnTZuUJWySzBEnWCg6X2TJG7zO-c5S8NdyRVip8br5YvWYZb3AkCpH2K7OdAX80AZ36gBsL552hxuZRtmFY-68iwn-ESSyvtSyqLf1RcvFa55S4lzOUzCDRM",
  },
  {
    id: "p3",
    title: "Local Maize",
    vendorId: "auntie-agnes",
    vendor: "Auntie Agnes",
    category: "Grains",
    categoryId: "grains",
    tags: ["maize", "grain", "staple"],
    description:
      "Locally grown maize — great for ugali and other household staples. Carefully dried and bagged by local farmers.",
    deliveryEstimate: "25 minutes",
    price: "KES 170.00/bag",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuCE2vx0omfIVX_cxMw3zT-Hocpu96iI4Gg3YTPbjpWBwpR9VPY9bl3mSAIv46Z1CGFL9geypRsb9U6KLa4qBnHnOkhQjzNVAuzxa6i2th8D2mvIxvAZpt7EuWfA_ZfI3H0HBzb9ljHYCXk5-morYzFkjCdsWkWQUYPWcN-9LM-cUkgeqQyBdaa1LOOC7PmqVdXdsuyfrRkIHrx_Lt6vR4HXtY3M5RptiygBw5sK6p6F42NKZK5j1wZPo5yTYqy_1L1KfQ4-OP8BTz0",
  },
  {
    id: "p4",
    title: "Cow Milk",
    vendorId: "uncle-david",
    vendor: "Uncle David",
    category: "Dairy",
    categoryId: "dairy",
    tags: ["milk", "dairy", "fresh"],
    description:
      "Fresh cow milk delivered from trusted local dairy producers. Ideal for drinking, cooking and baking.",
    deliveryEstimate: "25 minutes",
    price: "KES 60.00/L",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuC-4kZZF-70sStKShTAUuldwKdpu0w5V9vvTbxPLXAOgzJS9T506opmPQMB4NHK2HVsZJXpTsvQBkVGzuTPZrVeoj1PWuyzkRW0-o2z9rmZEWcv8AJAIaqrmb_K66TNu5vZhxg1oBSMyMglb_1Fsh-1C3n97R7YNDP6IbWtLVW5X7a5rzVFn9ioTP2SvQ4E_KXxJFFLg-yDlEWCtH3UfodK9i7qf0zYoHkXj-UYYcaG1r7h7Hfee2lmo4I1wPETSp1lX7TTUkpiw5c",
  },
  {
    id: "p5",
    title: "Fresh Tomatoes (Vine)",
    vendorId: "mama-rose",
    vendor: "Mama Rose",
    category: "Vegetables",
    categoryId: "vegetables",
    tags: ["tomato", "vine", "vegetables"],
    description:
      "Vine tomatoes — slightly sweeter and perfect for sauces and fresh salads.",
    deliveryEstimate: "25 minutes",
    price: "KES 150.00/kg",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuBV8gBbKDa7cnMo9Dd_h-fyu4f1jiSE04nHoEkLNmImaNTqW_itR65qLuIFDIy4loHjhJGzzmb0dRdiodmUR4SR4tObd-gXkt64n3DsrJoy1DjfS74qMY9Tfg0xfB_d8-9Nq8CQqOVLD7FqjVurOP6UI1rZCj-Qe6GCrmx87UmvQdPA6VXx_Zmhn2zxzE_Nhi0FgYDA-CnO7ZXYrbubdEE72AIpZh9pqmyWoPqkUeFvjSsWV3Sp5NDBK2wLd_VXxHmMemnOdC3EKcU",
  },
  {
    id: "p6",
    title: "Ripe Bananas (Cavendish)",
    vendorId: "farmer-john",
    vendor: "Farmer John",
    category: "Fruits",
    categoryId: "fruits",
    tags: ["banana", "fruit", "bunch"],
    description:
      "Sweet Cavendish bananas — a reliable snack and baking ingredient.",
    deliveryEstimate: "25 minutes",
    price: "KES 80.00/bunch",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuATQit1JrF5Jnyt4wkvgo4gg9AE35WZUHYu4bkP8Ug9C24i6Hq1pNoyB6sLrOU8lTrlw08oS_T1yAyCSoFN6GBDhXyWuTyePSown1zYI1IdMrIa_s7q3R85HYOD-V4TQtSPgpFWQ4LJFw-8rwhCMVpOnTZuUJWySzBEnWCg6X2TJG7zO-c5S8NdyRVip8br5YvWYZb3AkCpH2K7OdAX80AZ36gBsL552hxuZRtmFY-68iwn-ESSyvtSyqLf1RcvFa55S4lzOUzCDRM",
  },
  {
    id: "p7",
    title: "Heirloom Tomatoes",
    vendorId: "mama-rose",
    vendor: "Mama Rose",
    category: "Vegetables",
    categoryId: "vegetables",
    tags: ["tomato", "heirloom", "gourmet"],
    price: "KES 180.00/kg",
    description:
      "Premium heirloom tomatoes — great for salads and gourmet cooking.",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuBV8gBbKDa7cnMo9Dd_h-fyu4f1jiSE04nHoEkLNmImaNTqW_itR65qLuIFDIy4loHjhJGzzmb0dRdiodmUR4SR4tObd-gXkt64n3DsrJoy1DjfS74qMY9Tfg0xfB_d8-9Nq8CQqOVLD7FqjVurOP6UI1rZCj-Qe6GCrmx87UmvQdPA6VXx_Zmhn2zxzE_Nhi0FgYDA-CnO7ZXYrbubdEE72AIpZh9pqmyWoPqkUeFvjSsWV3Sp5NDBK2wLd_VXxHmMemnOdC3EKcU",
  },
  {
    id: "p8",
    title: "Plantain Bananas",
    vendorId: "farmer-john",
    vendor: "Farmer John",
    category: "Fruits",
    categoryId: "fruits",
    tags: ["plantain", "cooking", "fruit"],
    description:
      "Starchy plantains good for frying and cooking — a kitchen staple in many homes.",
    deliveryEstimate: "25 minutes",
    price: "KES 80.00/bunch",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuATQit1JrF5Jnyt4wkvgo4gg9AE35WZUHYu4bkP8Ug9C24i6Hq1pNoyB6sLrOU8lTrlw08oS_T1yAyCSoFN6GBDhXyWuTyePSown1zYI1IdMrIa_s7q3R85HYOD-V4TQtSPgpFWQ4LJFw-8rwhCMVpOnTZuUJWySzBEnWCg6X2TJG7zO-c5S8NdyRVip8br5YvWYZb3AkCpH2K7OdAX80AZ36gBsL552hxuZRtmFY-68iwn-ESSyvtSyqLf1RcvFa55S4lzOUzCDRM",
  },
  {
    id: "p9",
    title: "Dried Maize (2kg)",
    vendorId: "auntie-agnes",
    vendor: "Auntie Agnes",
    category: "Grains",
    categoryId: "grains",
    tags: ["maize", "dry", "bag"],
    description:
      "A 2kg bag of dried maize — ideal for small households and quick restocking.",
    deliveryEstimate: "25 minutes",
    price: "KES 170.00/bag",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuCE2vx0omfIVX_cxMw3zT-Hocpu96iI4Gg3YTPbjpWBwpR9VPY9bl3mSAIv46Z1CGFL9geypRsb9U6KLa4qBnHnOkhQjzNVAuzxa6i2th8D2mvIxvAZpt7EuWfA_ZfI3H0HBzb9ljHYCXk5-morYzFkjCdsWkWQUYPWcN-9LM-cUkgeqQyBdaa1LOOC7PmqVdXdsuyfrRkIHrx_Lt6vR4HXtY3M5RptiygBw5sK6p6F42NKZK5j1wZPo5yTYqy_1L1KfQ4-OP8BTz0",
  },
  {
    id: "p10",
    title: "Garden Tomatoes",
    vendorId: "mama-rose",
    vendor: "Mama Rose",
    category: "Vegetables",
    categoryId: "vegetables",
    tags: ["tomato", "garden"],
    price: "KES 150.00/kg",
    description:
      "Hand-picked garden tomatoes — everyday quality for soups and salads.",
    deliveryEstimate: "25 minutes",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuBV8gBbKDa7cnMo9Dd_h-fyu4f1jiSE04nHoEkLNmImaNTqW_itR65qLuIFDIy4loHjhJGzzmb0dRdiodmUR4SR4tObd-gXkt64n3DsrJoy1DjfS74qMY9Tfg0xfB_d8-9Nq8CQqOVLD7FqjVurOP6UI1rZCj-Qe6GCrmx87UmvQdPA6VXx_Zmhn2zxzE_Nhi0FgYDA-CnO7ZXYrbubdEE72AIpZh9pqmyWoPqkUeFvjSsWV3Sp5NDBK2wLd_VXxHmMemnOdC3EKcU",
  },
  {
    id: "p11",
    title: "Sweet Bananas",
    vendorId: "farmer-john",
    vendor: "Farmer John",
    category: "Fruits",
    categoryId: "fruits",
    tags: ["banana", "sweet"],
    description:
      "Sweet bananas — great for kids and quick snacks. Perfectly ripened.",
    deliveryEstimate: "25 minutes",
    price: "KES 80.00/bunch",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuATQit1JrF5Jnyt4wkvgo4gg9AE35WZUHYu4bkP8Ug9C24i6Hq1pNoyB6sLrOU8lTrlw08oS_T1yAyCSoFN6GBDhXyWuTyePSown1zYI1IdMrIa_s7q3R85HYOD-V4TQtSPgpFWQ4LJFw-8rwhCMVpOnTZuUJWySzBEnWCg6X2TJG7zO-c5S8NdyRVip8br5YvWYZb3AkCpH2K7OdAX80AZ36gBsL552hxuZRtmFY-68iwn-ESSyvtSyqLf1RcvFa55S4lzOUzCDRM",
  },
  {
    id: "p12",
    title: "Packaged Maize",
    vendorId: "auntie-agnes",
    vendor: "Auntie Agnes",
    category: "Grains",
    categoryId: "grains",
    tags: ["maize", "package"],
    description: "Packaged maize — cleaned and sealed for convenience.",
    deliveryEstimate: "25 minutes",
    price: "KES 170.00/bag",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuCE2vx0omfIVX_cxMw3zT-Hocpu96iI4Gg3YTPbjpWBwpR9VPY9bl3mSAIv46Z1CGFL9geypRsb9U6KLa4qBnHnOkhQjzNVAuzxa6i2th8D2mvIxvAZpt7EuWfA_ZfI3H0HBzb9ljHYCXk5-morYzFkjCdsWkWQUYPWcN-9LM-cUkgeqQyBdaa1LOOC7PmqVdXdsuyfrRkIHrx_Lt6vR4HXtY3M5RptiygBw5sK6p6F42NKZK5j1wZPo5yTYqy_1L1KfQ4-OP8BTz0",
  },
  {
    id: "p13",
    title: "Full Cream Milk",
    vendorId: "uncle-david",
    vendor: "Uncle David",
    category: "Dairy",
    categoryId: "dairy",
    tags: ["milk", "dairy", "full-cream"],
    description:
      "Full cream milk from grass-fed cows — great for families and coffee lovers.",
    deliveryEstimate: "25 minutes",
    price: "KES 60.00/L",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuC-4kZZF-70sStKShTAUuldwKdpu0w5V9vvTbxPLXAOgzJS9T506opmPQMB4NHK2HVsZJXpTsvQBkVGzuTPZrVeoj1PWuyzkRW0-o2z9rmZEWcv8AJAIaqrmb_K66TNu5vZhxg1oBSMyMglb_1Fsh-1C3n97R7YNDP6IbWtLVW5X7a5rzVFn9ioTP2SvQ4E_KXxJFFLg-yDlEWCtH3UfodK9i7qf0zYoHkXj-UYYcaG1r7h7Hfee2lmo4I1wPETSp1lX7TTUkpiw5c",
  },
];

export const RECOMMENDATIONS = [
  {
    id: "c1",
    title: "Carrots",
    vendorId: "uncle-david",
    vendor: "Uncle David",
    price: "Ksh 120/kg",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuBXCZvWtdsQmpyBWpEI5RZpad-a9VQX1MRY7Mv7-n2AoaJ2A3-2PlLT2d4kssEFw9LylQL26qM7BKnE3ugQh_XCJqgI6S69DOrkECVbb4jU0qk49AsI8pyEwMfnmw5TcrE1fD4eufVbWLBoXutUKcrmG2WdSlDlxPWZc8BtSE6myAal7ZCz2LQ4cfrpZLTLZqBPuV75HmniwT_aI5hUP3l3Wga3WqKDCn2tYptSK8Yk2qVWzzBbhkLoOYHcpvc1RSHlLIeihsGevBM",
  },
  {
    id: "c2",
    title: "Spinach",
    price: "Ksh 80/bunch",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuBQIR22AE8QJNGrRu1z6UliX3LFrzXCKkTvrLesBFFvmMPXStRx2C-_xKm9w9oJqr6ccZqT3FHFvo6CnDJHXWsPzqaSWWhBkpiWIa_JgLnXgm2nMWoKLG0FEK-nO_SOjaSEwNqUUGKvqstHcsU0fZCdzkWeLBzJ8qbfZnkOuuXEmZqjDc-GC0eYl-qruFvh0dv4yOy7eQYxlexNDSjRhQpcPaTZ8up3ZANm2cItVmz6L2ZiXx0D3xVVYyIf7xGNFF_VNJjhI-epYk8",
  },
  {
    id: "c3",
    title: "Potatoes",
    price: "Ksh 60/kg",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuDO73HmGSXSPK6p8MeYqLkUHDQPgRTFDMSKQMYfcpSvgRv0ooEDqt5XgQSvFq5JPIO_PSV1svPidfymRRvCk42AXIUkOP-4r3o5SELv_zgtXZdbuou2d92tKEYvFSQ3WDrUGsUGBalqw-0_zy35Z-Suf0CMhxxFukdTZHwSb0QQSEh3z3tCKumL-8BZX6vOykH79l-JwStb6g-NNJ4M89bZ1bymRP1bGO4qzYf551SkOoLMlyBoO1plFFZ7g0WgoCXrzvXeEm9V47o",
  },
  {
    id: "c4",
    title: "Onions",
    price: "Ksh 50/kg",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuBZ7kQ1HaJ5z5Ak9PjndRarFocnJ6gARZAwK7eUQyD4NALZwWw2Nc6ac5WYcWjB_cs2oQy4jrmgqOR_wh72Khlz0nivy759bvcO4SX1Azy94XVCeO_XdnhCxkmnsudjXah8tVgVrrwS-TImhcjNY9JB7D7pJMY-NdvwJZ3GptMl4yRKyONeJYZnbl8wz-LzDKMm43BO7PxxxEWNKelrlTvvJA_Y1LSgo8Q2tgFNj8fKFjkKrwsArmrDwEoBVfszml2hV5ccX1cGeq8",
  },
  {
    id: "c5",
    title: "Tomatoes",
    price: "Ksh 100/kg",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuBxzUH_puxqM6Rcs-h__RfZBty4j3HgBY1QCxGSrT4USlVH9XGLef_KWMZt-qGEDka5ds2A-IMvy3E4TFD8Xzht7ugDskLCtpgd0Butkf_kZD0PgIPBTK_cL1956P7M8HXTeUePcpHgmpPW2lU59lnQpxMGQfe4iQVMF8nMrluulUDWbsOvIhO0V4eydFyl6YvIZcm--tpzOB3z5EBz0rHH100HBnJhruUDO-PseGd_hImHdXgSObjPpYo4j0VNvihHZZxltT1-1II",
  },
];
